version: '3.8'
services:
  movies:
    image: bhagyalaxmi109/train
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image:bhagyalaxmi109/movies
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: bhagyalaxmi109/recharge
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: bhagyalaxmi109/dth
    ports:
      - "84:80"
    deploy:
      replicas: 3
