version: '3.8'
services:
  movies:
    image: bhagyalaxmi109/movies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: bhagyalaxmi109/dth:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image:bhagyalaxmi109/train:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image:bhagyalaxmi109/recharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
